name = "bhanu"
#main = "src/index.js"
#account_id = "89dc1f6511deb4895b78ad46555d682d"
#workers_dev = true
compatibility_date = "2024-10-22"
pages_build_output_dir = ".svelte-kit/cloudflare"

[dev]
port = 8080
local_protocol = "http"
